version: 2.1

jobs:
  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small
    steps:
      - checkout
      - run: sudo apk add findutils  # Install find command
      - run: find .  # Debug: Print the directory structure
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  sonarqube_workflow:
    jobs:
      - sonarqube
