jobs:
  sonarqube:
    working_directory: ~/build
    docker:
      - image: circleci/python:3.9  # Or another image with more utilities
    resource_class: small
    steps:
      - checkout
      - run: find .  # Debug: Prints the directory structure
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."
