# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  say-hello:
    docker:
      - image: cimg/node:latest  # Using a Node.js image for JavaScript
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  run-tests:
    docker:
      - image: cimg/node:latest  # Node.js image for running JavaScript tests
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install  # Install project dependencies
      - run:
          name: Run Tests
          command: npm test  # Run your tests

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: small
    steps:
      - checkout  # Check out the code from the repository
      - run:
          name: Run SonarCloud Scan
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

# Orchestrate jobs using workflows
workflows:
  version: 2
  say-hello-workflow: 
    jobs:
      - say-hello
      - run-tests
      - sonarqube:
          requires:
            - run-tests  # Ensure that the Sonar scan runs after the tests
