version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:16  # Use the appropriate Node.js version
    steps:
      - checkout  # Pulls your repo code to the CircleCI environment
      - run:
          name: Install dependencies
          command: |
            cd Backend  # Make sure to navigate to the correct directory if needed
            npm install  # Install the dependencies
      - run:
          name: Install Jest globally
          command: |
            cd Backend  # Ensure you're in the correct directory
            npm install -g jest  # Install Jest globally to avoid permission issues
      - run:
          name: Run Jest tests
          command: |
            cd Backend  # Again, ensure you're in the correct directory
            chmod +x ./node_modules/.bin/jest  # Ensure Jest is executable
            ./node_modules/.bin/jest --coverage  # Run Jest directly, avoiding potential path issues

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: small
    steps:
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  version: 2
  test:
    jobs:
      - run_tests  # First run the tests
      - sonarqube  # Then run SonarQube analysis
