version: 2.1

jobs:
  sonarqube-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: small
    steps:
      - checkout
      - run:
          name: Run SonarQube Analysis
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Starting SonarQube analysis for branch: $SONAR_BRANCH"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url="https://sonarcloud.io" \
              -Dsonar.sources="." \
              -Dsonar.exclusions="**/node_modules/**,**/tests/**" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.qualitygate.wait=true

workflows:
  version: 2
  sonar-analysis-workflow:
    jobs:
      - sonarqube-scan
