version: 2.1

jobs:
  sonarqube:
    working_directory: ~/build
    docker:
      - image: sonarsource/sonar-scanner-cli
    resource_class: small  # Adjust to medium or large if needed
    steps:
      - run: find .  # Check out the source code
      - attatch_workspace: 
          at: ~/workspace
          # Debug: Print the directory structure
      - run: |
          # Set the branch to main if CIRCLE_BRANCH is not defined
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          # Run the SonarQube analysis
          sonar-scanner \
          -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
          -Dsonar.organization="$SONAR_ORG" \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.exclusions="**/android/**,**/ios/**" \
          -Dsonar.login="$SONAR_TOKEN" \
          -Dsonar.branch.name="$SONAR_BRANCH" \
          -Dsonar.sources="."

workflows:
  sonarqube_workflow:
    jobs:
      - sonarqube
