version: 2.1

jobs:
  run_tests:
    docker:
      - image: circleci/node:16  # Use the appropriate Node.js version
    steps:
      - checkout  # Pulls your repo code to the CircleCI environment
      - run:
          name: Install dependencies
          command: |
            cd Backend  # Ensure we are in the correct directory
            npm install  # Install the dependencies, including Jest
      - run:
          name: Ensure Jest is executable
          command: |
            cd Backend
            chmod +x ./node_modules/.bin/jest  # Ensure the Jest binary has execute permissions
      - run:
          name: Run Jest tests
          command: |
            cd Backend
            ./node_modules/.bin/jest --coverage  # Explicitly run Jest

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: small
    steps:
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

workflows:
  version: 2
  test:
    jobs:
      - run_tests  # First run the tests
      - sonarqube  # Then run SonarQube analysis
