version: 2.1

# Define the jobs in CircleCI
jobs:
  # Job for running Jest tests
  test:
    docker:
      - image: circleci/node:16 # Using Node.js Docker image to run tests
    steps:
      - checkout # Get the code from your repository
      - run:
          name: Install dependencies
          command: npm install # Install all the dependencies listed in package.json
      - run:
          name: Run Jest tests
          command: npm test # Run the test command (which is "jest --coverage" in package.json)

  # Job for SonarQube analysis
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: small
    steps:
      - checkout # Get the code from your repository
      - run:
          name: Run SonarQube analysis
          command: |
            SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
            echo "Sonar branch value is: $SONAR_BRANCH"
            echo "Sonar org value is: $SONAR_ORG"
            sonar-scanner \
              -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
              -Dsonar.organization="$SONAR_ORG" \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.exclusions="**/node_modules/**,**/tests/**,**/android/**,**/ios/**" \
              -Dsonar.login="$SONAR_TOKEN" \
              -Dsonar.branch.name="$SONAR_BRANCH" \
              -Dsonar.sources="."

# Define workflows for orchestrating jobs
workflows:
  version: 2
  sonar-analysis:
    jobs:
      - test   # Run tests first
      - sonarqube:
          requires:
            - test  # Ensure SonarQube analysis runs only after tests
