# CircleCI Pipeline Configuration

This project uses CircleCI for continuous integration. The configuration follows the 2.1 version of CircleCI's pipeline process engine.

## Jobs

### 1. `say-hello`
This job runs a basic command to output a greeting message. Below are the details:

- **Docker Image**: Uses `cimg/base:current` as the execution environment.
- **Steps**:
  - **Checkout**: Checks out the code from the repository.
  - **Run Command**: Executes the command `echo Hello, World!` to display a greeting message.

### CircleCI Configuration (`config.yml`)
```yaml
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
