version: 2.1

# Define the jobs
jobs:
  # Job for running tests
  run_tests:
    docker:
      - image: circleci/node:16  # Use the appropriate Node.js version
    steps:
      - checkout  # This pulls your repo code to the CircleCI environment
      - run:
          name: Install dependencies
          command: |
            cd Backend  # Make sure to navigate to the correct directory if needed
            npm install
      - run:
          name: Run Jest tests
          command: |
            cd Backend  # Again, ensure you're in the correct directory
            npm test  # This should now work with the test script defined in your package.json

  # Job for SonarQube scan
  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: small
    steps:
      - run: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

# Define the workflows
workflows:
  version: 2
  test:
    jobs:
      - run_tests
      - sonarqube:
          requires:
            - run_tests
