version: 2.1

# Define jobs
jobs:
  say-hello:
    docker:
      - image: circleci/python:3.8
    steps:
      - run: echo "Hello, world!"

  sonarqube:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    resource_class: small
    steps:
      - checkout  # Check out the code from the repository
      - run:
        name: Run SonarCloud Scan
        command: |
          SONAR_BRANCH="${CIRCLE_BRANCH:-main}"
          echo "Sonar branch value is: $SONAR_BRANCH"
          echo "Sonar org value is: $SONAR_ORG"
          sonar-scanner \
            -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
            -Dsonar.organization="$SONAR_ORG" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.exclusions="**/android/**,**/ios/**" \
            -Dsonar.login="$SONAR_TOKEN" \
            -Dsonar.branch.name="$SONAR_BRANCH" \
            -Dsonar.sources="."

# Orchestrate jobs using workflows
workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
      - sonarqube:
          requires:
            - say-hello  # Ensure that the Sonar scan runs after the hello job
